---
- name: install ovpn, zip and rsa
  hosts: all
  become: yes
  
  tasks:
  - name: update linux
    shell: apt-get update

  - name: upgrade linux
    shell: apt-get upgrade

  - name: install ovpn
    yum: name=openvpn state=latest 

  - name: install zip
    yum: name=zip state=latest

  - name: download easy-rsa
    get_url: url=https://github.com/OpenVPN/easy-rsa/archive/master.zip dest=/home/vpn_admin

  - name: unzip rsa
    shell: unzip master.zip